add function

diff --git a/fix_chunk b/fix_chunk
--- a/fix_chunk
+++ b/fix_chunk
@@ -139,15 +139,25 @@ dump_chunk_data()
 
 validate_chunk_data()
 {
+    retval=1
     if [[ $# < 1 ]]
     then
         echo "validate_chunk_data need arg: chunkid"
+        return 1
     fi
     chunkid=$1
-    if [ -f "${chunkid}/${chunkid}.copy1" ]
+    if cmp -s "${chunkid}/${chunkid}.copy1" "${chunkid}/${chunkid}.copy2"
     then
-        :
+        echo "cmp ${chunkid} OK"
+        if strings "${chunkid}/${chunkid}.copy1" | grep "$chunkid" > /dev/null
+        then
+            retval=0
+        fi
+    else
+        echo "cmp ${chunkid} BAD"
+        retval=2
     fi
+    return $retval
 }
 
 inject_chunk_data()
@@ -155,12 +165,23 @@ inject_chunk_data()
     if [[ $# < 1 ]]
     then
         echo "validate_chunk_data need arg: chunkid"
+        return 1
     fi
     chunkid=$1
-    if [ -f "${chunkid}/${chunkid}.copy1" ]
+    if [ ! -f "${chunkid}/${chunkid}.info" ]
     then
-        :
+        echo "${chunkid}/${chunkid}.info not find"
+        return 2
     fi
+    if ! validate_chunk_data "$chunkid"
+    then
+        echo "chunk ${chunkid} data validation failed"
+        return 3
+    fi
+    # get chunk segments info
+    eval $(awk '/primary/{printf "zone=%s\n",$2};/sealedTime:/{printf "sealedTime=\047%s\047\n",$2}' $chunkid/${chunkid}.info)
+    echo "zone      : $zone"
+    echo "sealedTime: $sealedTime"
 }
 
 while read -u 99 chunkid
